# -*- coding: utf-8 -*-
"""Build a copyright-safe synthetic demo PDF + sample output packages (no MinerU required).

Sample packages are generated through the real packaging modules
(``pdf_excel.excel_writer`` / ``pdf_excel.pipeline.write_notes`` / ``pdf_excel.names``)
so they always match actual output naming and note contents:

  examples/demo_output/demo_sample/      output_language: zh (default)
  examples/demo_output/demo_sample_en/   output_language: en
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

DEMO_DIR = ROOT / "examples" / "demo"
OUT_BASE = ROOT / "examples" / "demo_output"
PACKAGE_DIRS = {
    "zh": OUT_BASE / "demo_sample",
    "en": OUT_BASE / "demo_sample_en",
}

TABLE_CAPTION = "Sample oxide composition"
TABLE_DATA = [
    ["Sample", "SiO2", "Al2O3", "Fe2O3", "CaO", "MgO", "w/% sum"],
    ["S-01", "45.2", "22.1", "8.3", "3.1", "1.2", "79.9"],
    ["S-02", "48.0", "20.5", "7.9", "2.8", "1.0", "80.2"],
    ["S-03", "51.4", "18.7", "6.2", "2.1", "0.9", "79.3"],
    ["S-04", "39.8", "25.0", "9.1", "4.0", "1.5", "79.4"],
    ["S-05", "42.6", "23.3", "8.0", "3.4", "1.3", "78.6"],
]

DEMO_NOTE = {
    "zh": (
        "## 示例说明",
        "本示例包由 `examples/build_demo.py` 生成，数据全部虚构，不来自任何学位论文。",
    ),
    "en": (
        "## Demo note",
        "This sample package is generated by `examples/build_demo.py`. "
        "All numbers are fictional — no thesis data is included.",
    ),
}


def build_pdf(path: Path) -> None:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )
    styles = getSampleStyleSheet()
    story = []
    story.append(Paragraph("pdf-excel synthetic demo (not a real paper)", styles["Title"]))
    story.append(Spacer(1, 8 * mm))
    story.append(
        Paragraph(
            "Table 1 " + TABLE_CAPTION + " — fictional data for the open-source demo only.",
            styles["Heading2"],
        )
    )
    story.append(Spacer(1, 4 * mm))

    t = Table(TABLE_DATA, hAlign="LEFT")
    t.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.9, 0.9, 0.95)),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(t)
    story.append(Spacer(1, 10 * mm))
    story.append(
        Paragraph(
            "This PDF is generated by examples/build_demo.py so newcomers can try the pipeline "
            "without copyrighted theses. Numbers are fictional.",
            styles["Normal"],
        )
    )
    doc.build(story)


def _table_html() -> str:
    head = "".join(f"<th>{h}</th>" for h in TABLE_DATA[0])
    body = "".join(
        "<tr>" + "".join(f"<td>{v}</td>" for v in row) + "</tr>" for row in TABLE_DATA[1:]
    )
    return f"<table><tr>{head}</tr>{body}</table>"


def _write_crop(raw_dir: Path, filename: str) -> None:
    """Draw a tiny synthetic table screenshot with Pillow when available."""
    try:
        from PIL import Image, ImageDraw
    except ImportError:  # pragma: no cover
        (raw_dir / "README.txt").write_text(
            "Synthetic table crop would go here. Run build_demo.py with Pillow for PNG.\n",
            encoding="utf-8",
        )
        return
    img = Image.new("RGB", (900, 320), "white")
    draw = ImageDraw.Draw(img)
    draw.rectangle([10, 10, 890, 310], outline="black", width=2)
    x0, y0, cw, rh = 20, 30, 120, 36
    for c, h in enumerate(TABLE_DATA[0]):
        draw.text((x0 + c * cw, y0), h, fill="black")
    for r, row in enumerate(TABLE_DATA[1:]):
        for c, val in enumerate(row):
            draw.text((x0 + c * cw, y0 + (r + 1) * rh), val, fill="black")
    img.save(raw_dir / filename)


def build_sample_package(language: str) -> Path:
    """Generate one sample package through the real packaging modules."""
    from pdf_excel.excel_writer import write_excel
    from pdf_excel.models import TableItem
    from pdf_excel.names import get_texts
    from pdf_excel.pipeline import write_notes

    texts = get_texts(language)
    out_dir = PACKAGE_DIRS[language]
    if out_dir.exists():
        shutil.rmtree(out_dir)
    raw_dir = out_dir / texts["tables_dir"]
    fig_dir = out_dir / texts["images_dir"]
    raw_dir.mkdir(parents=True)
    fig_dir.mkdir(parents=True)

    crop_name = f"{texts['table_word']}1_Sample_oxide_composition.png"
    _write_crop(raw_dir, crop_name)

    table = TableItem(
        index=1,
        page_idx=0,
        caption=TABLE_CAPTION,
        caption_raw=[TABLE_CAPTION],
        footnote=[],
        html_body=_table_html(),
        img_path=crop_name,
        bbox=None,
    )
    write_excel([table], out_dir / "demo_sample.xlsx", language=language)

    notes_path = write_notes(
        out_dir,
        "demo_sample",
        "examples/demo/demo_sample.pdf",
        [table],
        image_count=0,
        issues=[],
        language=language,
    )
    title, body = DEMO_NOTE[language]
    with notes_path.open("a", encoding="utf-8") as f:
        f.write(f"\n\n{title}\n\n{body}\n")

    (fig_dir / ".gitkeep").write_text("", encoding="utf-8")
    return out_dir


def main() -> None:
    pdf_path = DEMO_DIR / "demo_sample.pdf"
    build_pdf(pdf_path)
    print("Wrote", pdf_path)
    for language in PACKAGE_DIRS:
        out = build_sample_package(language)
        print(f"Wrote {language} package under", out)


if __name__ == "__main__":
    main()
