# -*- coding: utf-8 -*-
"""Build a copyright-safe synthetic demo PDF + sample output package (no MinerU required)."""

from __future__ import annotations

import shutil
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, Side
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

ROOT = Path(__file__).resolve().parents[1]
DEMO_DIR = ROOT / "examples" / "demo"
OUT_DIR = ROOT / "examples" / "demo_output" / "demo_sample"


def build_pdf(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )
    styles = getSampleStyleSheet()
    story = []
    story.append(Paragraph("pdf-excel synthetic demo (not a real paper)", styles["Title"]))
    story.append(Spacer(1, 8 * mm))
    story.append(
        Paragraph(
            "Table 1 Sample oxide composition (synthetic data for open-source demo only).",
            styles["Heading2"],
        )
    )
    story.append(Spacer(1, 4 * mm))

    data = [
        ["Sample", "SiO2", "Al2O3", "Fe2O3", "CaO", "MgO", "w/% sum"],
        ["S-01", "45.2", "22.1", "8.3", "3.1", "1.2", "79.9"],
        ["S-02", "48.0", "20.5", "7.9", "2.8", "1.0", "80.2"],
        ["S-03", "51.4", "18.7", "6.2", "2.1", "0.9", "79.3"],
        ["S-04", "39.8", "25.0", "9.1", "4.0", "1.5", "79.4"],
        ["S-05", "42.6", "23.3", "8.0", "3.4", "1.3", "78.6"],
    ]
    t = Table(data, hAlign="LEFT")
    t.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.9, 0.9, 0.95)),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(t)
    story.append(Spacer(1, 10 * mm))
    story.append(
        Paragraph(
            "This PDF is generated by examples/build_demo.py so newcomers can try the pipeline "
            "without copyrighted theses. Numbers are fictional.",
            styles["Normal"],
        )
    )
    doc.build(story)


def build_sample_package() -> None:
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    raw = OUT_DIR / "原始表格"
    figs = OUT_DIR / "图片"
    raw.mkdir(parents=True)
    figs.mkdir(parents=True)

    # Copy marketing original-table style image if present as a stand-in crop
    asset = ROOT / "docs" / "assets" / "qc-original-table.png"
    if asset.is_file():
        # Keep demo package self-contained with a small synthetic table image instead of thesis crop
        pass

    # Build a tiny table screenshot via reportlab -> use PDF page is heavy; write a simple xlsx-only package
    # and a placeholder text note for 原始表格 when image not generated.
    # Generate a clean synthetic table image with reportlab to PNG via canvas
    from reportlab.lib.pagesizes import landscape
    from reportlab.pdfgen import canvas as pdfcanvas

    # Prefer PNG for 原始表格: draw with reportlab on a one-page PDF then users open PDF;
    # simpler: write HTML-like grid as xlsx and copy demo note image from a generated PNG using pillow if available.
    try:
        from PIL import Image, ImageDraw, ImageFont

        img = Image.new("RGB", (900, 320), "white")
        draw = ImageDraw.Draw(img)
        draw.rectangle([10, 10, 890, 310], outline="black", width=2)
        headers = ["Sample", "SiO2", "Al2O3", "Fe2O3", "CaO", "MgO", "w/% sum"]
        rows = [
            ["S-01", "45.2", "22.1", "8.3", "3.1", "1.2", "79.9"],
            ["S-02", "48.0", "20.5", "7.9", "2.8", "1.0", "80.2"],
            ["S-03", "51.4", "18.7", "6.2", "2.1", "0.9", "79.3"],
            ["S-04", "39.8", "25.0", "9.1", "4.0", "1.5", "79.4"],
            ["S-05", "42.6", "23.3", "8.0", "3.4", "1.3", "78.6"],
        ]
        x0, y0, cw, rh = 20, 30, 120, 36
        for c, h in enumerate(headers):
            draw.text((x0 + c * cw, y0), h, fill="black")
        for r, row in enumerate(rows):
            for c, val in enumerate(row):
                draw.text((x0 + c * cw, y0 + (r + 1) * rh), val, fill="black")
        crop_path = raw / "表1_Sample_oxide_composition.png"
        img.save(crop_path)
    except Exception:
        (raw / "README.txt").write_text(
            "Synthetic table crop would go here. Run build_demo.py with Pillow for PNG.\n",
            encoding="utf-8",
        )

    # Excel matching package rules
    wb = Workbook()
    ws = wb.active
    ws.title = "表1_Sample_oxide"
    ws["A1"] = "标题: Table 1 Sample oxide composition (synthetic)"
    ws["A2"] = "页码: 1"
    thin = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin"),
    )
    header_font = Font(bold=True)
    data = [
        ["Sample", "SiO2", "Al2O3", "Fe2O3", "CaO", "MgO", "w/% sum"],
        ["S-01", "45.2", "22.1", "8.3", "3.1", "1.2", "79.9"],
        ["S-02", "48.0", "20.5", "7.9", "2.8", "1.0", "80.2"],
        ["S-03", "51.4", "18.7", "6.2", "2.1", "0.9", "79.3"],
        ["S-04", "39.8", "25.0", "9.1", "4.0", "1.5", "79.4"],
        ["S-05", "42.6", "23.3", "8.0", "3.4", "1.3", "78.6"],
    ]
    start = 4
    for r_i, row in enumerate(data):
        for c_i, val in enumerate(row):
            cell = ws.cell(row=start + r_i, column=c_i + 1, value=val)
            cell.border = thin
            cell.alignment = Alignment(horizontal="center", vertical="center")
            if r_i == 0:
                cell.font = header_font
    xlsx = OUT_DIR / "demo_sample.xlsx"
    wb.save(xlsx)

    (OUT_DIR / "转换说明.md").write_text(
        """# demo_sample — 转换说明

- 源 PDF: `examples/demo/demo_sample.pdf`（仓库内合成样例，虚构数据）
- 写入 Excel 的表格数: **1**
- Excel: `demo_sample.xlsx`
- 原始表格图片目录: `原始表格/`
- 文中图片目录: `图片/`

## 表格清单

### 表1: Table 1 Sample oxide composition (synthetic)
- 页码: 1
- 状态: 示例交付包（可对照 `原始表格/` 做质检演示）

## 质检提醒

自动转换不等于交付完成。请对照 `原始表格/` 检查表头与数值。

## 问题与限制

本次为开源演示包，数据全部虚构，不来自任何学位论文。
""",
        encoding="utf-8",
    )

    (figs / ".gitkeep").write_text("", encoding="utf-8")


def main() -> None:
    pdf_path = DEMO_DIR / "demo_sample.pdf"
    build_pdf(pdf_path)
    build_sample_package()
    print("Wrote", pdf_path)
    print("Wrote package under", OUT_DIR)


if __name__ == "__main__":
    main()
