#!/usr/bin/env bash
# Safe, isolated MinerU CLI install for TablePack (pdf-excel).
# Creates .venv-mineru, installs official mineru[all], writes config.yaml.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
VENV="$ROOT/.venv-mineru"

echo "==> TablePack: install MinerU CLI (isolated venv)"
echo "    Root: $ROOT"

PYTHON=""
for c in python3.12 python3.11 python3.10 python3 python; do
  if command -v "$c" >/dev/null 2>&1; then
    if "$c" -c 'import sys; raise SystemExit(0 if sys.version_info>=(3,10) else 1)'; then
      PYTHON="$c"
      break
    fi
  fi
done
if [[ -z "$PYTHON" ]]; then
  echo "ERROR: Need Python 3.10+. Install python3 and re-run." >&2
  exit 1
fi
echo "==> Using: $PYTHON ($($PYTHON -V))"

if [[ ! -d "$VENV" ]]; then
  echo "==> Creating venv: $VENV"
  "$PYTHON" -m venv "$VENV"
fi

# shellcheck disable=SC1091
source "$VENV/bin/activate"
python -m pip install -U pip setuptools wheel
python -m pip install -U uv
echo "==> Installing MinerU (official mineru[all])"
# https://github.com/opendatalab/MinerU
uv pip install -U "mineru[all]"
python -m pip install -r "$ROOT/requirements.txt"

MINERU_BIN="$VENV/bin/mineru"
if [[ ! -x "$MINERU_BIN" ]]; then
  echo "WARN: mineru binary missing; try: python -m mineru --help"
  MINERU_BIN="mineru"
else
  "$MINERU_BIN" --help | head -n 8 || true
fi

cat > "$ROOT/config.yaml" <<EOF
# Auto-generated by scripts/install_mineru.sh — safe to edit
root: $ROOT
pdf_dir: pdf
output_dir: output
work_dir: work/mineru_raw
mineru_bin: $MINERU_BIN
python_bin: $VENV/bin/python

backend: pipeline
method: auto
language: ch
enable_table: true
enable_formula: false
drop_empty_tables: true
skip_existing_excel: false
wipe_output_package: true
EOF

echo ""
echo "Done."
echo "Activate:  source .venv-mineru/bin/activate"
echo "Smoke:     python -m pdf_excel --dry-config"
echo "Demo:      cp examples/demo/demo_sample.pdf pdf/ && python -m pdf_excel demo_sample"
echo "Docs:      docs/INSTALL.md"
