#Requires -Version 5.1
<#
.SYNOPSIS
  Safe, isolated MinerU CLI install for TablePack (pdf-excel).

.DESCRIPTION
  Creates a dedicated virtualenv (default: .venv-mineru under the repo),
  installs official MinerU via uv/pip, and writes config.yaml mineru_bin.

  Does NOT modify system Python packages outside the venv.
  Does NOT download private PDFs.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts/install_mineru.ps1
#>

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $Root

$VenvDir = Join-Path $Root ".venv-mineru"
$Py = $null

Write-Host "==> TablePack: install MinerU CLI (isolated venv)" -ForegroundColor Cyan
Write-Host "    Root: $Root"

# Prefer py launcher 3.10–3.12
foreach ($ver in @("3.12", "3.11", "3.10")) {
    try {
        $c = & py "-$ver" -c "import sys; print(sys.executable)" 2>$null
        if ($LASTEXITCODE -eq 0 -and $c) { $Py = $c.Trim(); break }
    } catch {}
}
if (-not $Py) {
    $Py = (Get-Command python -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source)
}
if (-not $Py) {
    throw "Python 3.10+ not found. Install from https://www.python.org/downloads/ and re-run."
}

Write-Host "==> Using Python: $Py"
& $Py -c "import sys; v=sys.version_info; assert v>=(3,10), 'Need Python 3.10+'; print(sys.version)"

if (-not (Test-Path $VenvDir)) {
    Write-Host "==> Creating venv: $VenvDir"
    & $Py -m venv $VenvDir
}

$VenvPy = Join-Path $VenvDir "Scripts\python.exe"
$VenvPip = Join-Path $VenvDir "Scripts\pip.exe"
if (-not (Test-Path $VenvPy)) { throw "venv python missing: $VenvPy" }

Write-Host "==> Upgrading pip / installing uv"
& $VenvPy -m pip install -U pip setuptools wheel
& $VenvPy -m pip install -U uv

Write-Host "==> Installing MinerU (official package mineru[all])"
# Official quick-start style: https://github.com/opendatalab/MinerU
& $VenvPy -m uv pip install -U "mineru[all]"

$MineruExe = Join-Path $VenvDir "Scripts\mineru.exe"
if (-not (Test-Path $MineruExe)) {
    # fallback name
    $MineruExe = Join-Path $VenvDir "Scripts\mineru.exe"
}
if (-not (Test-Path $MineruExe)) {
    Write-Host "WARN: mineru.exe not found under Scripts. Checking module entry..." -ForegroundColor Yellow
    & $VenvPy -m mineru --help 2>&1 | Select-Object -First 5
} else {
    Write-Host "==> mineru CLI: $MineruExe"
    & $MineruExe --help 2>&1 | Select-Object -First 8
}

Write-Host "==> Installing TablePack (this repo) into same venv"
& $VenvPy -m pip install -r (Join-Path $Root "requirements.txt")

# Write config.yaml pointing at this mineru
$ConfigPath = Join-Path $Root "config.yaml"
$mineruPath = if (Test-Path $MineruExe) { $MineruExe -replace '\\', '/' } else { "mineru" }
@"
# Auto-generated by scripts/install_mineru.ps1 — safe to edit
root: $($Root -replace '\\', '/')
pdf_dir: pdf
output_dir: output
work_dir: work/mineru_raw
mineru_bin: $mineruPath
python_bin: $($VenvPy -replace '\\', '/')

backend: pipeline
method: auto
language: ch
enable_table: true
enable_formula: false
drop_empty_tables: true
skip_existing_excel: false
wipe_output_package: true
"@ | Set-Content -Path $ConfigPath -Encoding utf8

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host "Activate venv:"
Write-Host "  .\.venv-mineru\Scripts\Activate.ps1"
Write-Host "Smoke test:"
Write-Host "  python -m pdf_excel --dry-config"
Write-Host "  python -m pdf_excel demo_sample   # after: copy examples\demo\demo_sample.pdf pdf\"
Write-Host ""
Write-Host "First MinerU run may download models automatically (official behavior)."
Write-Host "Docs: docs/INSTALL.md"
